### ISSUE TITLE
SPM Parser for BIDSProv

### ISSUE THREAD

**Issue by remiadon** [bids-standard/BEP028_BIDSprov#49]
**Is your feature request related to a problem? Please describe.**
Right now we provide short examples that relies on our model
To get faster in the inclusion/discussion of new examples we need to automate their translation into .jsonld or .turtle files that respect BEP028 

**Describe the solution you'd like**
We want a parser that 
- takes .m files as input, as those provided in [nidm-results](https://github.com/incf-nidash/nidmresults-examples/)
- outputs a valid .jsonld file

This parse will have to be **updated with regard to the specification**

**TODO**
- [x] get spm_default and spm_groups_ols
- [x] get a first example, with each cell in the original .m file having an activity in the produced sidecar file
- [x] write a showcase example of a pipeline, eg. `parsing | visalisation`
- [x] write a github action to make sure the parser do not fail with a bunch of .m files (regression testing)

**Comment by remiadon** [comment]
@cmaumet I tried using the prov library again

Listing issues here:
1) Context , namespaces have to be added one by one
2) typed indexing doesnt seem really possible, neither when editing the structure nor when dumping it to a json-like format (we even have to convert it to non 1.1 JSON-LD in `visualize.py`)

**Comment by cmaumet** [comment]
Hi @remiadon, about 2 --> yes, this is related to prov library not being JSON-LD 1.1 compliant. To circumvent that issue we can use: prov -> rdflib -> pyld (as we did in the vizualisation tool). Does that help?

Not sure I understand 1, could you provide an example?

**Comment by remiadon** [comment]
@cmaumet  

about 1. I mean that we cannot point to a context, we have to download it a "manually" add prefixes to the document before updating it

Concerning 2. I agree with you, it's possible. But the point of using prov here is to build a valid document. If I follow you workflow I'll have to build a json document before passing it to prov. This only makes sure the document is valid before dumping it, but is not equivalent to checking for validity when building the document

I can add this anyway, that would still avoid some errors

**Comment by cmaumet** [comment]
Discussed on Feb 11 w/ @remiadon:
1/ As a workaround we can download the context file locally and then load with the prov library
2/ We'll create documents directly using the prov library (no need to build a json document first)
